apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-chronicles
  namespace: cicd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/drextrime/infra-backend:latest,frontend=ghcr.io/drextrime/infra-frontend:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DreXtrime/cluster-chronicles
    targetRevision: HEAD
    path: manifests/app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true