apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: "*"
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        persistence:
          enabled: true
          storageClass: standard
        volumeClaimTemplate:
          storageClassName: standard
          resources:
            requests:
              storage: 10Gi
        security:
          enabled: false
        xpack:
          security:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true