apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: "*"
    helm:
      values: |
        config:
          outputs: |
            [OUTPUT]
                Name es
                Match *
                Host elasticsearch-es-http
                Port 9200
                HTTP_User elastic
                HTTP_Passwd ${ELASTICSEARCH_PASSWORD}
                tls On
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix kubernetes
                Retry_Limit False
                Suppress_Type_Name On
        env:
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-es-elastic-user
                key: elastic
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true