apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: "0.57.9"
    helm:
      values: |
        config:
          outputs: |
            [OUTPUT]
                Name es
                Match *
                Host elasticsearch-master
                Port 9200
                Logstash_Format On
                Logstash_Prefix kubernetes
                Retry_Limit False
                tls On
                tls.verify Off
                HTTP_User elastic
                HTTP_Passwd ${ELASTICSEARCH_PASSWORD}
                Suppress_Type_Name On
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
        env:
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: password
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true