apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: infra-image-updater
  namespace: cicd
spec:
  applicationRefs:
    - namePattern: infra-app
      useAnnotations: true
  writeBackConfig:
    method: argocd