apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: "*"
    helm:
      values: |
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        elasticsearchHosts: "https://elasticsearch-master:9200"
        kibanaConfig:
          kibana.yml: |
            elasticsearch.hosts: ["https://elasticsearch-master:9200"]
            elasticsearch.username: "elastic"
            elasticsearch.password: "changeme"
            elasticsearch.ssl.verificationMode: none
            xpack.security.enabled: true
            server.ssl.enabled: false
        extraEnvs:
          - name: ELASTICSEARCH_HOSTS
            value: "https://elasticsearch-master:9200"
          - name: ELASTICSEARCH_USERNAME
            value: "elastic"
          - name: ELASTICSEARCH_PASSWORD
            value: "changeme"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true