apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://github.com/DreXtrime/cluster-chronicles
    targetRevision: HEAD
    path: manifests/logging
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true