apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: cicd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      values: |
        grafana:
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: ALL
        prometheus:
          prometheusSpec:
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector: {}
            ruleNamespaceSelector: {}
            ruleSelector: {}
        alertmanager:
          alertmanagerSpec:
            alertmanagerConfigSelector:
              matchLabels:
                alertmanagerConfig: discord
            alertmanagerConfigMatcherStrategy:
              type: None
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true